# Validatie tussen LU_8B_VAL en LU4_B_MAP

```{r echo = FALSE, message = FALSE, comment= "", error = FALSE, warning = FALSE}

library(tidyverse)
library(terra)
library(git2rdata)
library(plotly)
library(sf)
library(INBOtheme)
library(assertthat)
library(caret)
library(rprojroot)
library(devtools)
devtools::install_github("gbganalyst/forstringr")
library(forstringr)
library(flextable)

conflicted::conflicts_prefer(dplyr::pull)
conflicted::conflicts_prefer(dplyr::filter)

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, 
                  comment = "", error = FALSE)

git_root <- rprojroot::find_root(rprojroot::is_git_root)
source(file.path(git_root, "source/scripts/nca_functions.R"))

data_folder <-  file.path(git_root, "data")

script_folder <-  file.path(git_root, "scripts")


data <- read.csv(file.path(data_folder, 
                           "data_validation.csv"),
                 header = TRUE,
                 encoding = "UTF-8")

data_LU <- read.csv(file.path(data_folder, "raster_report_LUC.xlsx - report land use change categori.csv"), 
                        header = TRUE, encoding = "UTF-8")

# Functions 

source(file.path(git_root, "source/scripts/clustering_functions.R"))

source(file.path(git_root, "source/histmap_validation_quarto/scripts/clustering_functions.R"))

```


```{r}

test_clustering_8 <- clustering_area(clustering_method = c("mask_follow_up"),
                                     years = c(2022, 1989, 1981, 1969, 
                                               1904, 1873, 1850, 1774),
                                     variable = data$LU_8B_VAL,
                                     clustering_year = 1774,
                                     reference_year = 1774,
                                     reverse = TRUE)

test_clustering_8 <- test_clustering_8 %>% 
  mutate(reference_mask_follow_up_4 = paste0(
    str_sub(reference_mask_follow_up, 1, 1), 
    str_sub(reference_mask_follow_up, 4, 4), 
    str_sub(reference_mask_follow_up, 6, 6), 
    str_sub(reference_mask_follow_up, 8, 8))) %>% 
  rename(observed = reference, 
         prediction_mask_follow_up = reference_mask_follow_up_4) %>%
  mutate(prediction_mask_follow_up = factor(prediction_mask_follow_up)) %>% 
  select(observed, 
         prediction_mask_follow_up)

test_clustering_4 <- clustering_area(clustering_method = c("mask_follow_up"),
                                     years = c(2022, 1969, 
                                               1873, 1774),
                                     variable = data$LU4_B_MAP,
                                     clustering_year = 1774,
                                     reference_year = 1774,
                                     reverse = TRUE)

test_clustering <- cbind(test_clustering_8, 
                         test_clustering_4)


```


## User and producers accurcay using hand coded functions based on Olofsson et al.

```{r }
# Performing the clustering on the surface data 
## Hier zelfde probleem zijn de getallen van velue < 1000 oof values waarbij de 
## eerste cijfers moeten vervangen worden door "0"

data_LU <- data_LU %>% dplyr::filter(value >= 1000) %>% 
  mutate(value = as.character(value))

data_LU_clus <- clustering_area(data_LU$value, 
                                clustering_method = c("mask_follow_up",
                                                "mask_follow_up_intensity"), 
                                reverse = TRUE)

data_LU_merge <- merge(data_LU, data_LU_clus, 
                       by.x = "value", by.y = "reference") %>% 
  select(!c(Cumul_ha, Cumul_.))

## get area per cluster 

data_LU_area_clus <- data_LU_merge %>% 
  group_by(reference_mask_follow_up) %>% 
  summarise(area_ha = sum(ha, na.rm = TRUE), 
            area_m2 = sum(m2, na.rm = TRUE)) %>% 
  column_to_rownames(var = "reference_mask_follow_up")

```



```{r eval = TRUE, warning = TRUE}

check_class_level_match(test_clustering, data_LU_area_clus, 
                        reference_col = "reference_mask_follow_up", 
                        prediction_col = "prediction_mask_follow_up")


rare_preds <- get_rare_levels(test_clustering, 
                              prediction_mask_follow_up)
rare_refs  <- get_rare_levels(test_clustering,
                              reference_mask_follow_up)


rare_classes <- unique(c(rare_preds, rare_refs))

if(length(rare_classes) > 0){
  warning(paste("De clustering levels", 
                knitr::combine_words(rare_classes, and = " en "), 
                "tellen slechts 1 observatie."))
}

test_clustering <- test_clustering %>% 
  filter(!prediction_mask_follow_up %in% rare_classes, 
         !reference_mask_follow_up %in% rare_classes) %>% 
  droplevels()

data_LU_area_clus <- data_LU_area_clus[!rownames(data_LU_area_clus) %in%
                                         rare_classes,]


```


```{r }
intersect_levels <- lubridate::intersect(
  lubridate::intersect(levels(
    test_clustering$reference_mask_follow_up %>% droplevels()),
    levels(test_clustering$prediction_mask_follow_up
           %>% droplevels())),
  rownames(data_LU_area_clus))

test_clustering <- test_clustering %>% 
  dplyr::filter(reference_mask_follow_up %in% intersect_levels, 
                prediction_mask_follow_up %in% intersect_levels) %>% 
  droplevels()

data_LU_area_clus <- data_LU_area_clus[rownames(data_LU_area_clus) %in% 
                                         intersect_levels, ]

```

```{r }

res1 <- calculate_accuracy(mapdata = test_clustering$prediction_mask_follow_up,
                           refdata = test_clustering$reference_mask_follow_up)

```


```{r }

## Be sure that maparea and ma are ordered in the same manner

cm <- confusion_matrix(
  maparea = data_LU_area_clus$area_ha,
  ma = as.data.frame.matrix(res1$table)
)

```

```{r }
# using formulas Olafson 

## Overall accuracy

overall_acc <- calc_oa(
  maparea = data_LU_area_clus$area_ha,
  ma = as.data.frame.matrix(res1$table)
)

est <- overall_acc$oa_est
var <- overall_acc$oa_var

## User accuracy and producer accuracy

ua_pa_df <- calc_ua_pa(
  maparea = data_LU_area_clus$area_ha,
  ma = as.data.frame.matrix(res1$table)
)

tempdata <- flextable(ua_pa_df %>% 
                        mutate(across(
                          where(is.numeric), round, digits = 3)))
```

\newpage
\blandscape


```{r }

#| label: tbl-accu_own_funct_val_06
#| tbl-cap: !expr 'paste("UA en PA berekend met eigen formules gebaseerd op Olofsson et al.. De OA bedraagt ", round(est, 3) , " en heeft een variant van", round(var, 2),".")'

tempdata %>% set_table_properties(layout = "fixed")

```

\elandscape

## MAPAC 


```{r}

### check if areas are being used in the right strata cause for the functions the variables are not sorted

# using MPAC package
# aa <- mapac::aa_card(
#   data = test_clustering[, c("reference_mask_follow_up", 
#                              "prediction_mask_follow_up")],
#   w = data_LU_area_clus$area_ha/sum(data_LU_area_clus$area_ha),
#   strata = levels(factor(test_clustering$reference_mask_follow_up)),
#   area = sum(data_LU_area_clus$area_ha),
#   confusion_matrix = FALSE,
#   olofsson = TRUE
# )

aa <- mapac::aa_card(
  x = test_clustering$reference_mask_follow_up,
  m = test_clustering$prediction_mask_follow_up,
  w = data_LU_area_clus$area_ha/sum(data_LU_area_clus$area_ha),
  h = levels(factor(test_clustering$reference_mask_follow_up)),
  area = sum(data_LU_area_clus$area_ha),
  # confusion_matrix = FALSE,
  olofsson = TRUE
)

est <- aa$accuracy[1]
var <- aa$accuracy[2]

tempdata <- aa$stats 
row.names(tempdata) <- NULL
tempdata <- flextable(tempdata %>% mutate(across(
                          where(is.numeric), round, digits = 3)))

```
\newpage
\blandscape

```{r }
#| label: tbl-accu_own_mapac_val_06
#| tbl-cap: !expr 'paste("UA en PA berekend met MAPAC package. De OA bedraagt ", round(est, 3) , " en heeft een variant van", round(var, 2),".")'

tempdata %>% set_table_properties(layout = "fixed")
```
\elandscape

```{r eval = FALSE}
waldo::compare(overall_acc$oa_est, aa$accuracy[1])
waldo::compare(sqrt(overall_acc$oa_var), aa$accuracy[2]) ## No differences with MAPAC package


waldo::compare(unname(ua_pa_df$ua_est), aa$stats$ua, tolerance = 1e-10)
waldo::compare(unname(sqrt(ua_pa_df$ua_var)), aa$stats$ua_se, tolerance = 1e-3)
waldo::compare(unname(ua_pa_df$pa_est), aa$stats$pa, tolerance = 1e-10)
waldo::compare(unname(sqrt(ua_pa_df$pa_var)), aa$stats$pa_se, tolerance = 1e-3)

## No major differences with MAPAC package 


```

## Regeneses

```{r include = FALSE}

# estimate areas using ReGenesees
#################################
observed_changes_RD <- data.frame(
  map = as.factor(test_clustering$prediction_mask_follow_up),
  ref = as.factor(test_clustering$reference_mask_follow_up))   %>%
  mutate(
    map = factor(map, levels = sort(unique(c(levels(map), levels(ref))))),
    map = factor(map, levels = levels(map))
  ) %>% left_join(data_LU_area_clus %>% rownames_to_column(var = "ref"), 
                  by = "ref")

##  moet dit bij ref of bij map. Want dat gaat een verschil maken. Geen 
## groot verschil maar wel een verschil

n_h <- observed_changes_RD |>
  count(map)

maparea_RD <- data_LU_area_clus %>% rownames_to_column(var = "map") |>
  left_join(n_h, by = "map") |>
  mutate(
    ips = n / area_ha
  )

areas_df <- calc_areas(
  maparea = maparea_RD$area_ha,
  ma = as.data.frame.matrix(res1$table),
  pixelsize = 0.01 # each cell is 100 square meters = 0.01ha
)

prop_area_h <- observed_changes_RD |>
  distinct(map, area_ha) %>% 
  mutate(
    prop_area_ha = area_ha / sum(area_ha)
  )

observed_changes_RD <- left_join(observed_changes_RD %>% select(!c(area_ha)), 
                                 maparea_RD, by = "map")

# area Flanders
sum(prop_area_h$area_ha) ## kleine 10000 ha te weinig
sum(prop_area_h$area_m2)/10**6 ## kleine 100 km2 te weinig

# check if total area matches
sum(aa$area$area) - sum(prop_area_h$area_ha)

# create survey data.frame (long format)
# the variable oa is needed for estimation
svydata <- observed_changes_RD |>
  mutate(
    weights = 1 / ips,
    ids = paste0("id_", 1:n()),
    ones = 1,
    oa = as.numeric(map == ref)
  ) |>
  mutate(
    n_ref = n(),
    .by = ref
  ) |>
  inner_join(
    prop_area_h |> select(!c(area_ha)), by = join_by(map)
  ) %>% 
  mutate(
    map = factor(map), 
    ref = factor(ref)
  )

# create design object (could deal with more complex models)
design <- ReGenesees::e.svydesign(
  data = svydata,
  ids = ~ ids,
  strata = ~ map,
  weights = ~ weights,
  fpc = ~ ips)

# create dataframe containing marginal population totals
df.pop <- ReGenesees::pop.template(
  data = svydata,
  calmodel = ~ map - 1
) # see what the template should look like
ReGenesees::pop.desc(df.pop)
df.pop <- maparea_RD |>
  select(map, area_ha) |>
  pivot_wider(
    names_from = map,
    names_prefix = "map",
    values_from = area_ha) |>
  as.data.frame()

# calibrate on map marginal totals
# this adds the calibration weights to the design
cal <- ReGenesees::e.calibrate(
  design = design,
  df.population = df.pop,
  calmodel = ~ map - 1
)
summary(cal)
# but because in this case,
# the ratio between calibrated weights and initial weights equals 1;
# using cal or design in estimation will have the same result
# this is because inverse probability weights (N_h/n_h) already
# incorporate the map marginal totals per stratum
# this would not be the case if we calibrate on different strata or
# additional strata or use other/extra auxiliary information
# the calibration weights are stored in cal$variables$weights.cal
ReGenesees::g.range(cal)

# check calibration
ReGenesees::check.cal(cal)
summary(weights(cal))
ReGenesees::svystatTM(cal, ~ ones) # area of Flanders in 0.01 ha units

# estimate areas for ref
cal_ref_areas <- ReGenesees::svystatTM(
  design = cal,
  y =  ~ ref,
  estimator = "Total",
  conf.int = TRUE,
  deff = TRUE)
# note that above with y = ~ map would just recover known marginal totals (SE=0)
waldo::compare(aa$area$area, cal_ref_areas$Total, tolerance = 1e-10)
waldo::compare(aa$area$area_ci, 1.96*cal_ref_areas$SE, tolerance = 1e-4)
```

```{r include = FALSE}

# can we estimate the areas also via Bayes formula?
# $P(\text{referentie}=A) = \frac{UA}{PA}P(\text{kaart} = A)$
# first a naive attempt for just the estimator without SE
waldo::compare(
  aa$area$area, aa$stats$ua / aa$stats$pa * maparea_RD$area_ha,
  tolerance = 1e-4
) # only difference is one NA resulting from division pa 0
plot(aa$area$area, aa$stats$ua / aa$stats$pa * maparea_RD$area_ha)
abline(0, 1)
# how to estimate $\frac{UA}{PA}P(\text{kaart} = A)$ with ReGenesees?
# oa = n_jj = variable equalling one if ref == map, 0 otherwise
# n = n_i. = n_map the sample size per map stratum
# n_ref = n_.k = the number of ref cases
# UA / PA = (n_jj / n_i. ) / (n_jj / n_.k ) simplifies to n_.k / n_i.
# P(\text{kaart} = i) = area_i
#  n_.k / n_i. * area_i = sum over i of n_ik / n_i. * area_i
# compare with eq 9 Olofsson:
# W_i = area proportion of map class i = area_i / area_tot
# n_ik = cell count map i ref k
# n_i. = row sum map i
# area estimator for ref class k =
# total map area times sum over i (from 1 to 25) of W_i * n_ik/n_i.
# which again equals sum over i (from 1 to 25) of area_i * n_ik/n_i.

# note that area_i/n_i. are inverse probability weights
# because our survey data are in long format, we can
# represent n_ik as a vector of ones in combi with by = ~ref
# to obtain the same as before using either an expression in svystatL or
cal_ref_areas_checkL <- ReGenesees::svystatL(
  design = cal,
  expr =  expression(ones),
  by = ~ ref,
  conf.int = TRUE,
  deff = TRUE)
cal_ref_areas_checkTM <- ReGenesees::svystatTM(
  design = cal,
  y =  ~ ones,
  by = ~ ref,
  conf.int = TRUE,
  deff = TRUE)
waldo::compare(cal_ref_areas_checkL$ones, cal_ref_areas$Total)
waldo::compare(cal_ref_areas_checkTM$Total.ones, cal_ref_areas$Total)
waldo::compare(cal_ref_areas_checkL$SE.ones, cal_ref_areas$SE)
waldo::compare(cal_ref_areas_checkTM$SE.Total.ones, cal_ref_areas$SE)
```


```{r}
# can it also be used to calculate OA, UA and PA?
# OA: YES
cal_oa <- ReGenesees::svystatTM(
  design = cal,
  y =  ~ oa,
  estimator = "Mean",
  conf.int = TRUE,
  deff = TRUE)

est <- round(100*cal_oa$Mean, 3)
lower <- round(100*cal_oa$`CI.l(95%)`,3)
upper <- round(100*cal_oa$`CI.u(95%)`,3)

# waldo::compare(aa$accuracy[1], cal_oa$Mean, tolerance = 1e-10)
# waldo::compare(aa$accuracy[2], cal_oa$SE, tolerance = 1e-5)

# UA: YES
# (which need be estimated by row of contingency table which means by "map")
cal_ua <- ReGenesees::svystatTM(
  design = cal,
  y =  ~ oa,
  by = ~ map,
  estimator = "Mean",
  conf.int = TRUE,
  deff = TRUE)

# waldo::compare(aa$stats$ua, cal_ua$Mean.oa, tolerance = 1e-10)
# waldo::compare(aa$stats$ua_se, cal_ua$SE.Mean.oa, tolerance = 1e-2) # more conservative
# hist(aa$stats$ua_se -  cal_ua$SE.Mean.oa)
# plot(aa$stats$ua_se, cal_ua$SE.Mean.oa)
# abline(0, 1)

# PA
cal_pa <- ReGenesees::svystatTM(
  design = cal,
  y =  ~ oa,
  by = ~ ref,
  estimator = "Mean",
  conf.int = TRUE,
  deff = TRUE)
# waldo::compare(aa$stats$pa, cal_pa$Mean.oa, tolerance = 1e-10)
# waldo::compare(aa$stats$pa_se, cal_pa$SE.Mean.oa, tolerance = 1e-2)

# hist(aa$stats$pa_se -  cal_pa$SE.Mean.oa)
# plot(aa$stats$pa_se, cal_pa$SE.Mean.oa)
# abline(0, 1)

```

```{r fig.height = 9.5}
#| label: fig-UA_PA_regen_val_06
#| fig-cap: !expr 'paste("UA en PA berekend met Regenesees package. De OA bedraagt ", round(est, 3) , " met een 95% CI van [", lower, ";", upper, "]." )'



areas_df %>%
  inner_join(
    aa$stats, by = join_by(class)
  ) %>%
  # separate(
  #   class,
  #   c("class_p1", "class_p2"),
  #   sep = "-",
  #   remove = FALSE
  # ) %>%
  # mutate(change = class_p1 != class_p2) %>%
  mutate(
    class = reorder(
      sprintf(
        "%s\n(n = %s; ua = %s; pa = %s)",
        class, n_points, round(ua, 2), round(pa, 2)
        ),
      area_est_ha
    )
  ) %>%
  ggplot() +
  geom_pointrange(
    aes(
      x = class,
      y = area_est_ha,
      ymin = area_low_ha,
      ymax = area_high_ha
    )
  ) +
  ylab(expression(paste("estimated area in ", km^{2}))) + 
  scale_y_log10() +
  coord_flip() 
# +
#   facet_grid(paste0("Change: ", change) ~ ., scales = "free", space = "free")


```
